import { ScenarioAssumptions, ScenarioKey, AssumptionDefinition } from './roi-types';

export const SCENARIO_PRESETS: Record<ScenarioKey, ScenarioAssumptions> = {
  conservative: {
    turnoverReductionRate: 0.05,
    agencyReductionRate: 0.05,
    overtimeReductionRate: 0.05,
    pbjWorkflowReductionRate: 0.1,
    retainedTechAvoidedRate: 0.3,
    referralGrowthRate: 0.1,
    retentionMedicarePartAShare: 0.1,
    complianceExposureReductionRate: 0.25,
  },
  expected: {
    turnoverReductionRate: 0.15,
    agencyReductionRate: 0.15,
    overtimeReductionRate: 0.15,
    pbjWorkflowReductionRate: 0.4,
    retainedTechAvoidedRate: 0.6,
    referralGrowthRate: 0.3,
    retentionMedicarePartAShare: 0.25,
    complianceExposureReductionRate: 0.5,
  },
  opportunity: {
    turnoverReductionRate: 0.3,
    agencyReductionRate: 0.3,
    overtimeReductionRate: 0.3,
    pbjWorkflowReductionRate: 0.6,
    retainedTechAvoidedRate: 0.9,
    referralGrowthRate: 0.5,
    retentionMedicarePartAShare: 0.4,
    complianceExposureReductionRate: 0.75,
  },
};

export function getScenarioAssumptions(scenario: ScenarioKey): ScenarioAssumptions {
  return { ...SCENARIO_PRESETS[scenario] };
}

export const ASSUMPTION_DEFINITIONS: AssumptionDefinition[] = [
  {
    key: 'turnoverReductionRate',
    label: 'Turnover reduction rate',
    description: 'Percentage reduction in general employee turnover attributed to improved scheduling, streamlined onboarding, and enhanced recognition.',
    evidenceClass: 'influenced',
    isPercentage: true,
    min: 0,
    max: 0.5,
    step: 0.01,
    sourceLabel: 'Paycor customer averages; 2024 LTC workforce analysis.',
  },
  {
    key: 'agencyReductionRate',
    label: 'Agency hours reduction rate',
    description: 'Percentage reduction in premium agency hours accomplished through better staff scheduling, shift pick-up incentives, and faster recruiting.',
    evidenceClass: 'influenced',
    isPercentage: true,
    min: 0,
    max: 0.5,
    step: 0.01,
    sourceLabel: 'Paycor internal client scheduling utilization study.',
  },
  {
    key: 'overtimeReductionRate',
    label: 'Overtime hours reduction rate',
    description: 'Percentage reduction in overtime hours from automatic scheduling alerts, fatigue tracking, and shift equity controls.',
    evidenceClass: 'influenced',
    isPercentage: true,
    min: 0,
    max: 0.5,
    step: 0.01,
    sourceLabel: 'Paycor retail and healthcare labor studies.',
  },
  {
    key: 'pbjWorkflowReductionRate',
    label: 'PBJ preparation reduction rate',
    description: 'Percentage reduction in administrative labor required to format, audit and submit Payroll-Based Journal (PBJ) files to CMS.',
    evidenceClass: 'influenced',
    isPercentage: true,
    min: 0,
    max: 0.9,
    step: 0.05,
    sourceLabel: 'Paycor PBJ workflow compliance benchmarks.',
  },
  {
    key: 'retainedTechAvoidedRate',
    label: 'Confirmed tech-retirement rate',
    description: 'The portion of current annual technology spend that will be retired or not renewed upon moving to Paycor.',
    evidenceClass: 'direct',
    isPercentage: true,
    min: 0,
    max: 1.0,
    step: 0.05,
    sourceLabel: 'Requires prospect-by-prospect validation of active contracts.',
  },
  {
    key: 'referralGrowthRate',
    label: 'CMS-influenced referral rate',
    description: 'The portion of newly generated referrals resulting from an overall rating improvement that successfully convert to admissions.',
    evidenceClass: 'correlated',
    isPercentage: true,
    min: 0,
    max: 0.8,
    step: 0.05,
    sourceLabel: 'Medicare referral patterns study; separate from base ROI.',
  },
  {
    key: 'retentionMedicarePartAShare',
    label: 'Medicare Part A retention rate',
    description: 'The portion of Medicare Part A reimbursement protected or recovered through improved quality ratings and staff-retention stability.',
    evidenceClass: 'correlated',
    isPercentage: true,
    min: 0,
    max: 0.8,
    step: 0.05,
    sourceLabel: 'SNF Quality Measures and VBP study; separate from base ROI.',
  },
  {
    key: 'complianceExposureReductionRate',
    label: 'Compliance exposure reduction rate',
    description: 'Percentage reduction in estimated risk exposure of administrative or license penalties due to robust PBJ auditing and payroll trail records.',
    evidenceClass: 'influenced',
    isPercentage: true,
    min: 0,
    max: 0.95,
    step: 0.05,
    sourceLabel: 'Compliance audit benchmarks; separate from base ROI.',
  },
];
